"""
Preflight check for config.yaml -- run this BEFORE trusting a new or
changed config, especially after swapping the embedding model, reranker,
or LLM backend. Catches a broken setting in seconds instead of failing
partway through a multi-hour ingest, or silently running with the wrong
relevance thresholds.

Two stages:

  Stage 1 (default, no ingested data needed): does the configured
  embedding/sparse/reranker model actually load, is Qdrant reachable, is
  the LLM backend reachable, does project.repo_path exist, is ctags
  installed. Safe to run before ingest.py.

  Stage 2 (--calibrate, run AFTER ingest.py): measures real
  min_score_current thresholds against the CURRENTLY INGESTED collection --
  the same method used to calibrate Qwen3's thresholds by hand (see
  docs/DECISIONS.md, "Production Migration to Qwen3-Embedding-0.6B"): score
  a batch of deliberately off-topic probe questions and a batch of genuine
  on-topic questions, then suggest a threshold sitting between the two.
  On-topic probes are generated by the configured LLM from real sampled
  chunks, so this works for any codebase without hand-written questions --
  but it's a heuristic, not a substitute for real user-question data at
  scale; treat the suggested number as a starting point, not gospel.

Usage:
  python3 backend/check_config.py              # stage 1 only
  python3 backend/check_config.py --calibrate   # stage 1 + stage 2
"""
import sys
import shutil
import random

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))

from config import get_config, get_repo_path, get_current_collection_name

PASS, WARN, FAIL = "PASS", "WARN", "FAIL"
results = []


def check(name):
    def decorator(fn):
        def wrapped(*a, **kw):
            try:
                status, msg = fn(*a, **kw)
            except Exception as e:
                status, msg = FAIL, f"raised {type(e).__name__}: {e}"
            results.append((name, status, msg))
            icon = {"PASS": "✓", "WARN": "!", "FAIL": "✗"}[status]
            print(f"  [{icon}] {name}: {msg}")
            return status
        return wrapped
    return decorator


@check("config.yaml loads")
def check_config_loads():
    cfg = get_config()
    required = ["project", "qdrant", "embedding", "retrieval", "reranking", "llm"]
    missing = [k for k in required if k not in cfg]
    if missing:
        return FAIL, f"missing top-level keys: {missing}"
    return PASS, "all required sections present"


@check("project.repo_path exists")
def check_repo_path():
    from pathlib import Path
    p = Path(get_repo_path())
    if not p.is_dir():
        return FAIL, f"{p} is not a directory"
    if not (p / ".git").exists():
        return WARN, f"{p} exists but has no .git -- history features (history_ingest.py etc.) won't work"
    return PASS, str(p)


@check("Qdrant reachable")
def check_qdrant():
    from core.pipeline import get_client
    client = get_client()
    collections = client.get_collections()
    return PASS, f"connected, {len(collections.collections)} existing collection(s)"


@check("embedding model loads")
def check_embedding_model():
    from core.pipeline import get_model
    cfg = get_config()["embedding"]
    model = get_model()
    vec = model.encode("preflight check", prompt_name=cfg.get("query_prompt_name"))
    actual_dim = len(vec)
    configured_dim = cfg["dimension"]
    if actual_dim != configured_dim:
        return FAIL, (
            f"model produces {actual_dim}-dim vectors but config.yaml says "
            f"dimension: {configured_dim} -- fix the config, or ingest.py will "
            f"build a collection with the wrong vector size"
        )
    return PASS, f"{cfg['model_name']} loads, produces {actual_dim}-dim vectors as configured"


@check("sparse (BM25) model loads")
def check_sparse_model():
    from core.pipeline import get_sparse_model
    model = get_sparse_model()
    list(model.embed(["preflight check"]))
    return PASS, "loads and embeds"


@check("reranker model loads")
def check_reranker():
    from core.pipeline import get_reranker
    cfg = get_config().get("reranking", {})
    if not cfg.get("enabled", True):
        return WARN, "reranking.enabled is false -- skipped (not an error)"
    reranker = get_reranker()
    if reranker is None:
        return FAIL, "get_reranker() returned None despite reranking.enabled: true"
    reranker.predict([("preflight check", "some candidate text")])
    return PASS, f"{cfg.get('model_name')} loads and scores"


@check("LLM backend reachable")
def check_llm_backend():
    from generation.llm_backend import generate_text
    backend = get_config()["llm"]["backend"]
    reply = generate_text("Reply with exactly: OK", backend=backend)
    if not reply or not reply.strip():
        return FAIL, f"{backend} backend returned an empty response"
    return PASS, f"{backend} backend responded ({len(reply)} chars)"


@check("ingestion exclusions")
def check_exclusions():
    from core.file_exclusions import get_custom_exclude_patterns, get_gitignored_relpaths
    from pathlib import Path
    repo = get_repo_path()
    patterns = get_custom_exclude_patterns()
    sample = [str(p.relative_to(repo)) for p in list(Path(repo).rglob("*"))[:500] if p.is_file()]
    ignored_count = len(get_gitignored_relpaths(repo, sample))
    detail = f"{ignored_count}/{len(sample)} sampled files are gitignored by the target repo"
    if patterns:
        detail += f"; {len(patterns)} custom exclude_patterns configured: {patterns}"
    else:
        detail += "; no custom exclude_patterns configured"
    return PASS, detail


@check("Universal Ctags available")
def check_ctags():
    binary = get_config().get("ctags", {}).get("binary", "ctags")
    path = shutil.which(binary)
    if path is None:
        return WARN, f"'{binary}' not found on PATH -- cross-file symbol resolution will silently degrade (not a crash)"
    return PASS, path


@check("GPU (CUDA) availability")
def check_gpu():
    import torch
    if torch.cuda.is_available():
        return PASS, torch.cuda.get_device_name(0)
    return WARN, "no CUDA GPU detected -- embedding/reranking will run on CPU, slower but functional"


OFF_TOPIC_PROBES = [
    "how do I bake a chocolate cake",
    "what's the capital of France",
    "explain quantum entanglement",
    "best recipe for pasta carbonara",
    "how do I change a car tire",
    "what year did the Roman Empire fall",
]


def run_calibration():
    print("\n--- Stage 2: threshold calibration (needs an already-ingested collection) ---\n")
    from core.pipeline import get_client, get_model, get_query_prompt_name
    from generation.llm_backend import generate_text

    cfg = get_config()
    collection = get_current_collection_name()
    client = get_client()

    if not client.collection_exists(collection):
        print(f"  [✗] '{collection}' doesn't exist yet -- run ingest.py first, then re-run with --calibrate.")
        return 1

    count = client.count(collection_name=collection).count
    if count == 0:
        print(f"  [✗] '{collection}' exists but is empty -- run ingest.py first.")
        return 1

    model = get_model()
    prompt_name = get_query_prompt_name()
    backend = cfg["llm"]["backend"]

    def dense_score(query: str) -> float:
        vec = model.encode(query, prompt_name=prompt_name).tolist()
        hits = client.query_points(collection_name=collection, query=vec, using="dense", limit=1).points
        return hits[0].score if hits else 0.0

    print(f"  Sampling real chunks from '{collection}' ({count} points) to generate on-topic probes via {backend}...")
    sample_size = min(6, count)
    sampled, _ = client.scroll(collection_name=collection, limit=sample_size * 3, with_payload=True)
    random.shuffle(sampled)
    sampled = sampled[:sample_size]

    on_topic_scores = []
    for point in sampled:
        text = point.payload.get("text", "")[:800]
        if not text.strip():
            continue
        try:
            question = generate_text(
                "Here is a snippet from a real software project's code or docs. "
                "Write ONE short, natural question a user might genuinely ask that "
                "this snippet would help answer. Output ONLY the question, nothing else.\n\n"
                f"{text}",
                backend=backend,
            ).strip().strip('"')
        except Exception as e:
            print(f"    (skipped one sample -- LLM call failed: {e})")
            continue
        score = dense_score(question)
        on_topic_scores.append(score)
        print(f"    on-topic  {score:.3f}  | {question}")

    off_topic_scores = []
    for q in OFF_TOPIC_PROBES:
        score = dense_score(q)
        off_topic_scores.append(score)
        print(f"    off-topic {score:.3f}  | {q}")

    if not on_topic_scores:
        print("\n  [✗] Couldn't generate any on-topic probes (LLM calls failed) -- can't suggest a threshold.")
        return 1

    worst_on_topic = min(on_topic_scores)
    best_off_topic = max(off_topic_scores)
    print(f"\n  Worst on-topic score:  {worst_on_topic:.3f}")
    print(f"  Best off-topic score:  {best_off_topic:.3f}")

    if best_off_topic >= worst_on_topic:
        print(
            "\n  [!] Scores OVERLAP -- no clean gap between on-topic and off-topic here. "
            "This can happen with a small/narrow collection or ambiguous generated probes. "
            "Don't blindly trust a computed number in this case -- widen the sample or "
            "review manually before setting a threshold."
        )
        return 1

    suggested = round(best_off_topic + (worst_on_topic - best_off_topic) * 0.3, 2)
    current = get_config()["retrieval"].get("min_score_current")
    print(f"\n  Suggested min_score_current: {suggested}  (currently configured: {current})")
    print(
        "  This is a heuristic based on a handful of generated probes, not a large "
        "labeled set -- treat it as a starting point (paste it into config.yaml's "
        "retrieval.min_score_current), then sanity-check with a few real questions "
        "before trusting it fully. min_score_history should be checked separately "
        "once history is backfilled -- the same score distribution doesn't "
        "necessarily transfer from current-state chunks to diff/commit chunks."
    )
    return 0


def main():
    calibrate = "--calibrate" in sys.argv

    print("--- Stage 1: config sanity checks ---\n")
    check_config_loads()
    check_repo_path()
    check_qdrant()
    check_embedding_model()
    check_sparse_model()
    check_reranker()
    check_llm_backend()
    check_exclusions()
    check_ctags()
    check_gpu()

    failures = [r for r in results if r[1] == FAIL]
    warnings = [r for r in results if r[1] == WARN]
    print(f"\nStage 1: {len(results) - len(failures) - len(warnings)} passed, {len(warnings)} warning(s), {len(failures)} failure(s)")

    if failures:
        print("\nFix the failure(s) above before running ingest.py or starting the server.")
        sys.exit(1)

    if not calibrate:
        print("\nStage 1 clean. Run with --calibrate after ingest.py to also measure relevance thresholds.")
        sys.exit(0)

    exit_code = run_calibration()
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
